export enum Periority {
  NEGLIGIBLE = 'NEGLIGIBLE',
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}
export enum Status {
  OPEN = 'OPEN',
  UNREPRODUCIBLE = 'UNREPRODUCIBLE',
  PLANNED = 'PLANNED',
  ONGOING = 'ONGOING',
  FIXED = 'FIXED',
}
